import { BlockType, BlockDef, Tier } from './types';

export const BLOCK_DEFS: Record<number, BlockDef> = {
  [BlockType.Air]: {
    type: BlockType.Air,
    name: 'Air',
    color: 0x000000,
    hardness: 0,
    minTier: Tier.Stone,
    transparent: true,
    solid: false,
  },
  [BlockType.Grass]: {
    type: BlockType.Grass,
    name: 'Grass',
    color: 0x4a7c3f,
    hardness: 1,
    minTier: Tier.Stone,
    transparent: false,
    solid: true,
  },
  [BlockType.Dirt]: {
    type: BlockType.Dirt,
    name: 'Dirt',
    color: 0x8b6914,
    hardness: 1,
    minTier: Tier.Stone,
    transparent: false,
    solid: true,
  },
  [BlockType.Stone]: {
    type: BlockType.Stone,
    name: 'Stone',
    color: 0x888888,
    hardness: 2,
    minTier: Tier.Stone,
    dropItem: 'stone',
    transparent: false,
    solid: true,
  },
  [BlockType.OreRed]: {
    type: BlockType.OreRed,
    name: 'Copper Ore',
    color: 0xcc4444,
    hardness: 3,
    minTier: Tier.Red,
    dropItem: 'ore_red',
    transparent: false,
    solid: true,
    emissive: 0xcc4444,
    emissiveIntensity: 0.15,
  },
  [BlockType.OreOrange]: {
    type: BlockType.OreOrange,
    name: 'Iron Ore',
    color: 0xcc7722,
    hardness: 4,
    minTier: Tier.Orange,
    dropItem: 'ore_orange',
    transparent: false,
    solid: true,
    emissive: 0xcc7722,
    emissiveIntensity: 0.2,
  },
  [BlockType.OreYellow]: {
    type: BlockType.OreYellow,
    name: 'Gold Ore',
    color: 0xcccc22,
    hardness: 5,
    minTier: Tier.Yellow,
    dropItem: 'ore_yellow',
    transparent: false,
    solid: true,
    emissive: 0xcccc22,
    emissiveIntensity: 0.25,
  },
  [BlockType.OreGreen]: {
    type: BlockType.OreGreen,
    name: 'Emerald Ore',
    color: 0x22cc44,
    hardness: 6,
    minTier: Tier.Green,
    dropItem: 'ore_green',
    transparent: false,
    solid: true,
    emissive: 0x22cc44,
    emissiveIntensity: 0.3,
  },
  [BlockType.OreBlue]: {
    type: BlockType.OreBlue,
    name: 'Sapphire Ore',
    color: 0x2266cc,
    hardness: 7,
    minTier: Tier.Blue,
    dropItem: 'ore_blue',
    transparent: false,
    solid: true,
    emissive: 0x4488ff,
    emissiveIntensity: 0.35,
  },
  [BlockType.OreIndigo]: {
    type: BlockType.OreIndigo,
    name: 'Amethyst Ore',
    color: 0x6622cc,
    hardness: 8,
    minTier: Tier.Indigo,
    dropItem: 'ore_indigo',
    transparent: false,
    solid: true,
    emissive: 0x8844ff,
    emissiveIntensity: 0.4,
  },
  [BlockType.OreViolet]: {
    type: BlockType.OreViolet,
    name: 'Mythril Ore',
    color: 0x8822cc,
    hardness: 9,
    minTier: Tier.Violet,
    dropItem: 'ore_violet',
    transparent: false,
    solid: true,
    emissive: 0xaa44ff,
    emissiveIntensity: 0.5,
  },
  [BlockType.OreDiamond]: {
    type: BlockType.OreDiamond,
    name: 'Diamond Ore',
    color: 0xbbddff,
    hardness: 10,
    minTier: Tier.White,
    dropItem: 'ore_diamond',
    transparent: false,
    solid: true,
    emissive: 0xddeeff,
    emissiveIntensity: 0.6,
  },
  [BlockType.Bedrock]: {
    type: BlockType.Bedrock,
    name: 'Bedrock',
    color: 0x333333,
    hardness: Infinity,
    minTier: Tier.White,
    transparent: false,
    solid: true,
  },
  [BlockType.Ladder]: {
    type: BlockType.Ladder,
    name: 'Ladder',
    color: 0xaa8844,
    hardness: 1,
    minTier: Tier.Stone,
    dropItem: 'ladder',
    transparent: true,
    solid: false,
  },
  [BlockType.Teleport]: {
    type: BlockType.Teleport,
    name: 'Teleport Pad',
    color: 0x44eeff,
    hardness: Infinity,
    minTier: Tier.White,
    transparent: false,
    solid: true,
    emissive: 0x44eeff,
    emissiveIntensity: 0.8,
  },
};
