import { BlockType, OreDef, Tier } from './types';

/** Ore definitions: rarity increases with depth/tier */
export const ORE_DEFS: OreDef[] = [
  {
    blockType: BlockType.OreRed,
    tier: Tier.Red,
    minDepth: 1,
    maxDepth: 50,
    rarity: 0.08,
    clusterSize: [3, 8],
    sellPrice: 5,
  },
  {
    blockType: BlockType.OreOrange,
    tier: Tier.Orange,
    minDepth: 5,
    maxDepth: 50,
    rarity: 0.06,
    clusterSize: [3, 6],
    sellPrice: 12,
  },
  {
    blockType: BlockType.OreYellow,
    tier: Tier.Yellow,
    minDepth: 10,
    maxDepth: 50,
    rarity: 0.05,
    clusterSize: [2, 5],
    sellPrice: 25,
  },
  {
    blockType: BlockType.OreGreen,
    tier: Tier.Green,
    minDepth: 15,
    maxDepth: 50,
    rarity: 0.04,
    clusterSize: [2, 5],
    sellPrice: 50,
  },
  {
    blockType: BlockType.OreBlue,
    tier: Tier.Blue,
    minDepth: 22,
    maxDepth: 50,
    rarity: 0.03,
    clusterSize: [2, 4],
    sellPrice: 100,
  },
  {
    blockType: BlockType.OreIndigo,
    tier: Tier.Indigo,
    minDepth: 30,
    maxDepth: 50,
    rarity: 0.02,
    clusterSize: [1, 3],
    sellPrice: 200,
  },
  {
    blockType: BlockType.OreViolet,
    tier: Tier.Violet,
    minDepth: 38,
    maxDepth: 50,
    rarity: 0.015,
    clusterSize: [1, 3],
    sellPrice: 400,
  },
  {
    blockType: BlockType.OreDiamond,
    tier: Tier.White,
    minDepth: 45,
    maxDepth: 50,
    rarity: 0.008,
    clusterSize: [1, 2],
    sellPrice: 1000,
  },
];
